previews:
  generation: automatic
services:
  - type: web
    plan: free
    name: ip-logger
    runtime: python
    repo: https://github.com/LazaDX/iplogger.git
    branch: master
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn iplogger.wsgi"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: iplogger.settings
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: IPINFO_TOKEN
        sync: false