services:
     - type: web
       name: ip-logger
       env: python
       plan: free
       buildCommand: "pip install -r requirements.txt && python manage.py migrate"
       startCommand: "gunicorn iplogger.wsgi"
       envVars:
         - key: DJANGO_SETTINGS_MODULE
           value: iplogger.settings
         - key: DJANGO_DEBUG
           value: False
         - key: DJANGO_SECRET_KEY
           generateValue: true